import { AppLayout } from "@/components/app-layout";
import "dracula-ui/styles/dracula-ui.css";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-black">
        <AppLayout>{children}</AppLayout>
      </body>
    </html>
  );
}
